[profile.default]
  src = "src"
  out = "out"
  libs = ["lib"]
  no_match_test = 'testFork_|testForkFuzz_'
  solc_version = '0.8.26'
  evm_version = 'prague'
  ignored_warnings_from = ["lib"]
  optimizer = true
  optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
